import { IMG } from "@/lib/images";

export const SEED_CATEGORIES = [
  { name: "News", slug: "actualites", color: "#1a3896", order: 1, description: "National and local news from the Global South" },
  { name: "Sports", slug: "sports", color: "#2D6A4F", order: 2, description: "All African sports news" },
  { name: "Entertainment", slug: "divertissement", color: "#9B5DE5", order: 3 },
  { name: "Health", slug: "sante", color: "#00B4D8", order: 4 },
  { name: "Finance", slug: "finance", color: "#94563c", order: 5, description: "Economy and financial markets" },
  { name: "Technology", slug: "technologie", color: "#4361EE", order: 6 },
  { name: "World", slug: "monde", color: "#F77F00", order: 7, description: "International news" },
  { name: "Investigations", slug: "investigations", color: "#D62828", order: 8 },
  { name: "Opinion", slug: "opinion", color: "#6B6B6B", order: 9 },
  { name: "Multimedia", slug: "multimedia", color: "#1a3896", order: 10 },
  { name: "Local", slug: "local", color: "#588157", order: 11 },
  { name: "Special Reports", slug: "reportages-speciaux", color: "#94563c", order: 12 },
];

export const SEED_AUTHORS = [
  { name: "Ama Kouassi", slug: "ama-kouassi", bio: "Economics correspondent — Global South Watch, Abidjan." },
  { name: "Brice Ahi", slug: "brice-ahi", bio: "Senior reporter specializing in agriculture and rural development." },
  { name: "Kadi Traoré", slug: "kadi-traore", bio: "Tech and innovation journalist in West Africa." },
  { name: "Marie-Jo Bamba", slug: "marie-jo-bamba", bio: "Diaspora and society columnist." },
  { name: "Sékou Koné", slug: "sekou-kone", bio: "Political and institutional affairs correspondent." },
  { name: "Prof. Adjoua Mensah", slug: "adjoua-mensah", bio: "Economist and opinion columnist." },
];

export const SEED_ALERTS = [
  { text: "WAEMU tax reform: our exclusive investigation into the winners and losers", link: "/article/la-grande-reforme-fiscale-ouest-africaine-qui-gagne-qui-perd-dans-luemoa", order: 1 },
  { text: "AFCON 2027: Abidjan to host the final — official CAF decision", order: 2 },
  { text: "Wave and Orange Money announce historic merger", order: 3 },
  { text: "Google inaugurates its first data center in sub-Saharan Africa in Accra", order: 4 },
  { text: "AU Summit: roadmap for the continent's food self-sufficiency", order: 5 },
];

export interface SeedArticle {
  title: string;
  slug?: string;
  subtitle?: string;
  category: string;
  excerpt: string;
  content: string;
  tags: string[];
  image: string;
  isFeatured?: boolean;
  isTopStory?: boolean;
  isUrgent?: boolean;
  isEditorsChoice?: boolean;
  isPremium?: boolean;
  contentType?: "article" | "video" | "podcast" | "gallery";
  videoUrl?: string;
  authorIndex?: number;
}

export const SEED_ARTICLES: SeedArticle[] = [
  {
    title: "The great West African tax reform: who wins and who loses in WAEMU?",
    slug: "la-grande-reforme-fiscale-ouest-africaine-qui-gagne-qui-perd-dans-luemoa",
    subtitle: "In-depth analysis of the new common tax directives",
    category: "finance",
    excerpt: "An in-depth analysis of the new common tax directives for the eight member states of the Union. Our experts break down the stakes for businesses, households, and governments across the region.",
    content: `<p>The WAEMU member states have just adopted an unprecedented package of tax reforms since the creation of the monetary union. This overhaul affects VAT, corporate tax, and sectoral exemptions.</p>
    <h2>Differentiated impacts</h2>
    <p>Agri-food SMEs benefit from targeted relief, while extractive sectors see their tax advantages gradually reduced over five years.</p>
    <blockquote>« This reform aims to make the system fairer while preserving regional competitiveness. »</blockquote>
    <p>Our simulations show a net gain for urban middle-income households, but possible tensions in border areas.</p>`,
    tags: ["WAEMU", "economy", "taxation", "West Africa"],
    isFeatured: true,
    isTopStory: true,
    isUrgent: true,
    isEditorsChoice: true,
    isPremium: true,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=800&fit=crop",
    authorIndex: 0,
  },
  {
    title: "Wave and Orange Money announce merger: birth of Africa's first super-wallet",
    slug: "wave-et-orange-money-annoncent-leur-fusion-naissance-du-premier-super-portefeuille-africain",
    category: "finance",
    excerpt: "The deal would create an entity valued at over $8 billion, reshaping the FinTech landscape across the continent.",
    content: `<p>Two mobile money giants have just announced their intention to merge. The resulting entity would cover 24 countries and more than 180 million active users.</p>
    <h2>An expected consolidation</h2>
    <p>BCEAO and ARTP regulators must approve the deal by year-end. Analysts anticipate major synergies on cross-border transfers.</p>`,
    tags: ["FinTech", "Mobile Money", "merger", "Africa"],
    isTopStory: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&h=800&fit=crop",
    authorIndex: 0,
  },
  {
    title: "AFCON 2027: Félix Houphouët-Boigny Stadium to host the final, capacity raised to 60,000",
    slug: "can-2027-le-stade-felix-houphouet-boigny-accueillera-la-finale-capacite-portee-a-60-000",
    category: "sports",
    excerpt: "CAF has confirmed that Abidjan will host the continental tournament final after expansion work on the iconic stadium.",
    content: `<p>Côte d'Ivoire will host the AFCON 2027 final at the Félix Houphouët-Boigny Stadium, whose capacity will be increased to 60,000 seats. An investment of €120 million is planned.</p>`,
    tags: ["AFCON2027", "football", "Abidjan", "sport"],
    isTopStory: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Abidjan Tech Valley: 40 startups selected for the 2026 continental accelerator",
    slug: "abidjan-tech-valley-40-startups-selectionnees-pour-laccelerateur-continental-2026",
    category: "technologie",
    excerpt: "The program selects the most promising startups in West Africa for 12 months of support and a $2M fund.",
    content: `<p>Forty startups from 15 countries have been selected for the 2026 Abidjan Tech Valley cohort. Dominant sectors: agritech, digital health, and clean energy.</p>`,
    tags: ["startups", "tech", "Abidjan", "innovation"],
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "AU Summit: the continent adopts a roadmap for food self-sufficiency",
    slug: "sommet-de-lua-le-continent-adopte-une-feuille-de-route-pour-lautonomie-alimentaire",
    category: "monde",
    excerpt: "African heads of state adopted a five-year plan aiming to reduce food imports by 50% by 2031.",
    content: `<p>The extraordinary African Union summit resulted in a historic agreement on food self-sufficiency. The plan provides for $25 billion in public and private investment.</p>`,
    tags: ["AU", "agriculture", "food security", "Africa"],
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "Embezzlement of public funds: three ministers charged in construction contracts scandal",
    slug: "detournement-de-fonds-publics-trois-ministres-mis-en-examen-dans-laffaire-des-marches-de-construction",
    category: "investigations",
    excerpt: "Our eight-month investigation reveals a massive overbilling system in major infrastructure projects.",
    content: `<p>Three former ministers have been charged as part of a vast investigation into public construction contracts. Estimated losses exceed €400 million.</p>
    <h2>A sprawling network</h2>
    <p>Shell companies based in Dubai and Geneva allegedly laundered misappropriated funds over five years.</p>`,
    tags: ["investigation", "corruption", "infrastructure"],
    isTopStory: true,
    isUrgent: true,
    isEditorsChoice: true,
    isPremium: true,
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "Ivorian farmers turning cocoa into premium chocolate",
    slug: "ces-agriculteurs-ivoiriens-qui-transforment-le-cacao-en-chocolat-haut-de-gamme",
    category: "reportages-speciaux",
    excerpt: "A new generation of cocoa growers is disrupting the global chocolate market from plantations in Bélier.",
    content: `<p>In the Bélier region, family cooperatives now produce bean-to-bar chocolate exported to Europe and Asia. A model challenging the dominance of major processors.</p>`,
    tags: ["cocoa", "agriculture", "chocolate", "Côte d'Ivoire"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "RTS,S malaria vaccine: Côte d'Ivoire launches national mass vaccination campaign",
    slug: "vaccin-antipaludisme-rtss-la-cote-divoire-lance-sa-campagne-nationale-de-vaccination-de-masse",
    category: "sante",
    excerpt: "The Ministry of Health aims to vaccinate 2.5 million children in the first six months of the campaign.",
    content: `<p>Côte d'Ivoire becomes the first Francophone West African country to launch a mass malaria vaccination campaign with the RTS,S vaccine.</p>`,
    tags: ["health", "malaria", "vaccination"],
    isTopStory: true,
    image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "Google unveils its first sub-Saharan Africa data center in Accra",
    slug: "google-devoile-son-premier-data-center-dafrique-subsaharienne-installe-a-accra",
    category: "technologie",
    excerpt: "The $600 million investment positions Ghana as a regional digital hub.",
    content: `<p>Google has inaugurated its first sub-Saharan Africa data center in Accra. The facility will power cloud services for the entire West African region.</p>`,
    tags: ["Google", "data center", "Ghana", "tech"],
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Parliament passes personal data protection law",
    slug: "le-parlement-vote-la-loi-sur-la-protection-des-donnees-personnelles",
    subtitle: "A first in Francophone West Africa",
    category: "actualites",
    excerpt: "The bill transposes international data protection standards and creates an independent supervisory authority.",
    content: `<p>Parliament adopted the personal data protection law by a large majority, a first in the Francophone West African space.</p>`,
    tags: ["personal data", "politics", "GDPR"],
    isTopStory: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "AI for agriculture: Agrotech CI deploys voice assistant in Dioula and Baoulé",
    slug: "lia-au-service-de-lagriculture-agrotech-ci-deploie-son-assistant-vocal-en-dioula-et-baoule",
    category: "technologie",
    excerpt: "The app gives farmers personalized advice on crops, weather, and market prices.",
    content: `<p>Agrotech CI launches a multilingual voice assistant for smallholder farmers. The tool works offline and covers 12 main crops.</p>`,
    tags: ["AI", "agriculture", "innovation"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Should Francophone Africa rethink its public debt model?",
    slug: "faut-il-repenser-le-modele-de-la-dette-publique-en-afrique-francophone",
    category: "opinion",
    excerpt: "An economist's perspective on the limits of the current model and possible alternatives for Global South states.",
    content: `<p>African public debt has doubled in ten years. It is time to rethink borrowing mechanisms and repayment terms to free up resources for development.</p>`,
    tags: ["debt", "economy", "opinion"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "Ivoirians in France: how the second generation is reinventing ties with home",
    slug: "ivoiriens-de-france-comment-la-deuxieme-generation-reinvente-le-lien-avec-le-pays",
    category: "reportages-speciaux",
    excerpt: "Cross-portraits of eight young Franco-Ivoirians who chose to return home to start businesses.",
    content: `<p>They grew up in the Paris suburbs and chose to return to Abidjan to launch their startup or take over a family farm. Eight journeys telling the story of a changing diaspora.</p>`,
    tags: ["diaspora", "return", "entrepreneurship"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&h=800&fit=crop",
    authorIndex: 3,
  },
  {
    title: "Port of Abidjan: how it became West Africa's leading logistics hub",
    slug: "le-port-dabidjan-comment-il-est-devenu-le-premier-hub-logistique-dafrique-de-louest",
    category: "multimedia",
    excerpt: "Video report on the port's transformation into a continental logistics platform.",
    content: `<p>With 25 million tonnes of freight handled per year, the Port of Abidjan has become the commercial gateway to the West African hinterland.</p>`,
    tags: ["port", "logistics", "economy", "Abidjan"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    isFeatured: true,
    isTopStory: true,
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "Grand-Bassam UNESCO listing: extension of colonial heritage site officialized",
    slug: "grand-bassam-classee-au-patrimoine-mondial-lunesco-officialise-lextension-du-site-colonial",
    category: "local",
    excerpt: "The extension of the Grand-Bassam historic site strengthens Côte d'Ivoire's tourism and heritage appeal.",
    content: `<p>UNESCO has officialized the extension of the Grand-Bassam site to world heritage status, including newly restored colonial buildings.</p>`,
    tags: ["UNESCO", "heritage", "tourism", "Grand-Bassam"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200&h=800&fit=crop",
    authorIndex: 3,
  },
  {
    title: "UN adopts historic resolution on developing countries' sovereign debt",
    slug: "lonu-adopte-une-resolution-historique-sur-la-dette-souveraine-des-pays-en-developpement",
    category: "monde",
    excerpt: "The Security Council calls for coordinated restructuring of debt for the most vulnerable countries.",
    content: `<p>A historic resolution on sovereign debt was adopted at the UN, paving the way for fairer restructuring mechanisms for Global South countries.</p>`,
    tags: ["UN", "debt", "development"],
    image: "https://images.unsplash.com/photo-1540914124281-342587941389?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "Ligue 1 CI: ASEC wins Abidjan derby 3-1",
    slug: "ligue-1-ci-lasec-remporte-le-derby-dabidjan-3-1",
    category: "sports",
    excerpt: "ASEC Mimosas beat Africa Sports and reclaim the top of the Ivorian championship.",
    content: `<p>In a heated Abidjan derby, ASEC won 3-1 against Africa Sports at Robert-Champroux Stadium in front of 25,000 spectators.</p>`,
    tags: ["football", "ASEC", "Ligue 1", "Abidjan"],
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Sassandra deforestation: investigation reveals true scale of forest loss",
    slug: "deforestation-du-sassandra-lenquete-qui-revele-lampleur-reelle-des-pertes-forestieres",
    category: "investigations",
    excerpt: "Satellite imagery and local testimony document accelerated deforestation since 2020.",
    content: `<p>Our investigation cross-references satellite images, customs data, and villager testimony to quantify forest loss in the Sassandra region.</p>`,
    tags: ["environment", "deforestation", "investigation"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "Global South Talks: African debt under the economists' microscope",
    slug: "global-south-talks-la-dette-africaine-sous-le-microscope-des-economistes",
    category: "opinion",
    excerpt: "Podcast episode with three experts on sovereign debt restructuring in Africa.",
    content: `<p>In this episode, our guests debate restructuring mechanisms, the IMF's role, and alternatives proposed by Global South countries.</p>`,
    tags: ["podcast", "debt", "economy"],
    contentType: "podcast",
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "AfDB announces $800M financing for Ivorian agri-food SMEs",
    slug: "la-bad-annonce-un-financement-de-800mdollar-pour-les-pme-ivoiriennes-dans-le-secteur-agroalimentaire",
    category: "finance",
    excerpt: "The African Development Bank unlocks a major package for local processing and agri-food exports.",
    content: `<p>The AfDB confirms an $800 million loan to support Ivorian SMEs.</p>`,
    tags: ["AfDB", "SMEs", "agri-food"],
    image: IMG.agriculture,
    authorIndex: 0,
  },
  {
    title: "United Nations: Security Council meets urgently on Sahel situation",
    slug: "nations-unies-le-conseil-de-securite-se-reunit-en-urgence-sur-la-situation-au-sahel",
    category: "monde",
    excerpt: "Deteriorating security in the Sahel puts the UN before a humanitarian and political dilemma.",
    content: `<p>The Security Council is holding an extraordinary session on the Sahel crisis.</p>`,
    tags: ["UN", "Sahel", "security"],
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "Meta deploys WhatsApp Pay in Côte d'Ivoire with native CinetPay integration",
    slug: "meta-deploie-son-service-whatsapp-pay-en-cote-divoire-avec-integration-cinetpay-native",
    category: "technologie",
    excerpt: "Payment via WhatsApp arrives in Côte d'Ivoire through a partnership with CinetPay.",
    content: `<p>Meta launches WhatsApp Pay in Côte d'Ivoire with CinetPay.</p>`,
    tags: ["Meta", "WhatsApp", "FinTech"],
    image: IMG.tech,
    authorIndex: 2,
  },
  {
    title: "New meningitis cases in Bouaké: Health Ministry activates regional emergency protocol",
    slug: "nouveaux-cas-de-meningite-a-bouake-le-ministere-de-la-sante-active-le-protocole-durgence-regional",
    category: "sante",
    excerpt: "Facing a surge in cases, health authorities deploy an emergency response.",
    content: `<p>Emergency protocol activated after new meningitis cases in Bouaké.</p>`,
    tags: ["health", "meningitis", "Bouaké"],
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "Exclusive interview: Prime Minister responds to criticism of education reform",
    slug: "interview-exclusive-le-premier-ministre-repond-aux-critiques-sur-la-reforme-de-leducation",
    category: "actualites",
    excerpt: "The Prime Minister outlines the roadmap for national education reform.",
    content: `<p>Exclusive interview on education reform.</p>`,
    tags: ["politics", "education", "interview"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "The Elephants on the road to AFCON — report from the FIF training center",
    slug: "les-elephants-en-route-pour-la-can-reportage-dans-le-centre-de-preparation-de-la-fif",
    category: "sports",
    excerpt: "Inside the Ivorian national team's training center.",
    content: `<p>Report from the FIF training center.</p>`,
    tags: ["AFCON", "football"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Illegal gold mining in the north: documentary on clandestine networks",
    slug: "orpaillage-illegal-dans-le-nord-le-grand-documentaire-sur-les-filieres-clandestines",
    category: "investigations",
    excerpt: "Documentary on illegal gold mining networks and their consequences.",
    content: `<p>Video investigation into clandestine gold mining in the north of the country.</p>`,
    tags: ["investigation", "gold mining"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    isPremium: true,
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
];

export const SEED_NEWSLETTER = [
  { email: "lecteur1@example.com", preferences: ["general", "finance"] },
  { email: "lecteur2@example.com", preferences: ["sports", "general"] },
  { email: "redaction@globalsouthwatch.test", preferences: ["investigations", "opinion"] },
];
