import { IMG } from "@/lib/images";

export const SEED_CATEGORIES = [
  { name: "News", slug: "actualites", color: "#1a3896", order: 1, description: "National and local news from the Global South" },
  { name: "Politics", slug: "politique", color: "#1D3557", order: 2, description: "Political institutions, elections, and governance across the Global South" },
  { name: "Sports", slug: "sports", color: "#2D6A4F", order: 3, description: "All African sports news" },
  { name: "Culture", slug: "culture", color: "#6A4C93", order: 4, description: "Arts, literature, heritage, and cultural life across the Global South" },
  { name: "Entertainment", slug: "divertissement", color: "#9B5DE5", order: 5, description: "Music, film, arts, and entertainment from the Global South" },
  { name: "Health", slug: "sante", color: "#00B4D8", order: 6, description: "Public health, epidemics, and health systems across emerging economies" },
  { name: "Finance", slug: "finance", color: "#94563c", order: 7, description: "Economy and financial markets" },
  { name: "Technology", slug: "technologie", color: "#4361EE", order: 8, description: "Innovation, digital infrastructure, and startups" },
  { name: "World", slug: "monde", color: "#F77F00", order: 9, description: "International news" },
  { name: "Investigations", slug: "investigations", color: "#D62828", order: 10, description: "Accountability journalism and long-form probes" },
  { name: "Opinion", slug: "opinion", color: "#6B6B6B", order: 11, description: "Analysis, columns, and debate from experts and public intellectuals" },
  { name: "Multimedia", slug: "multimedia", color: "#1a3896", order: 12, description: "Video reports, podcasts, and visual storytelling" },
  { name: "Local", slug: "local", color: "#588157", order: 13, description: "City and regional stories beyond the capital" },
  { name: "Special Reports", slug: "reportages-speciaux", color: "#94563c", order: 14, description: "In-depth features and cross-border narrative journalism" },
  { name: "Africa", slug: "africa", color: "#1a3896", order: 15, description: "News, analysis, and investigations across the African continent" },
  { name: "Latin America", slug: "latin-america", color: "#2D6A4F", order: 16, description: "Coverage from Mexico to Patagonia" },
  { name: "South Asia", slug: "south-asia", color: "#E85D04", order: 17, description: "India, Pakistan, Bangladesh, Sri Lanka, and the wider subcontinent" },
  { name: "West Asia", slug: "west-asia", color: "#9B2226", order: 18, description: "Gulf states, Levant, Turkey, and Iran" },
];

export const SEED_AUTHORS = [
  { name: "Ama Kouassi", slug: "ama-kouassi", bio: "Economics correspondent — Global South Watch, Abidjan." },
  { name: "Brice Ahi", slug: "brice-ahi", bio: "Senior reporter specializing in agriculture and rural development." },
  { name: "Kadi Traoré", slug: "kadi-traore", bio: "Tech and innovation journalist in West Africa." },
  { name: "Marie-Jo Bamba", slug: "marie-jo-bamba", bio: "Diaspora and society columnist." },
  { name: "Sékou Koné", slug: "sekou-kone", bio: "Political and institutional affairs correspondent." },
  { name: "Prof. Adjoua Mensah", slug: "adjoua-mensah", bio: "Economist and opinion columnist." },
  { name: "Lucia Mendoza", slug: "lucia-mendoza", bio: "Latin America correspondent based in Bogotá." },
  { name: "Priya Sharma", slug: "priya-sharma", bio: "South Asia editor covering trade, tech, and public policy." },
  { name: "Omar Al-Hassan", slug: "omar-al-hassan", bio: "West Asia correspondent — energy, diplomacy, and regional security." },
];

export const SEED_ALERTS = [
  { text: "WAEMU tax reform: our exclusive investigation into the winners and losers", link: "/article/la-grande-reforme-fiscale-ouest-africaine-qui-gagne-qui-perd-dans-luemoa", order: 1 },
  { text: "AFCON 2027: Abidjan to host the final — official CAF decision", order: 2 },
  { text: "Wave and Orange Money announce historic merger", order: 3 },
  { text: "Google inaugurates its first data center in sub-Saharan Africa in Accra", order: 4 },
  { text: "AU Summit: roadmap for the continent's food self-sufficiency", order: 5 },
];

export interface SeedArticle {
  title: string;
  slug?: string;
  subtitle?: string;
  category: string;
  excerpt: string;
  content: string;
  tags: string[];
  image: string;
  isFeatured?: boolean;
  isTopStory?: boolean;
  isUrgent?: boolean;
  isEditorsChoice?: boolean;
  isPremium?: boolean;
  contentType?: "article" | "video" | "podcast" | "gallery";
  videoUrl?: string;
  gallery?: { url: string; caption?: string; credit?: string }[];
  authorIndex?: number;
}

export const SEED_ARTICLES: SeedArticle[] = [
  {
    title: "The great West African tax reform: who wins and who loses in WAEMU?",
    slug: "la-grande-reforme-fiscale-ouest-africaine-qui-gagne-qui-perd-dans-luemoa",
    subtitle: "In-depth analysis of the new common tax directives",
    category: "finance",
    excerpt: "An in-depth analysis of the new common tax directives for the eight member states of the Union. Our experts break down the stakes for businesses, households, and governments across the region.",
    content: `<p>The WAEMU member states have just adopted an unprecedented package of tax reforms since the creation of the monetary union. This overhaul affects VAT, corporate tax, and sectoral exemptions.</p>
    <h2>Differentiated impacts</h2>
    <p>Agri-food SMEs benefit from targeted relief, while extractive sectors see their tax advantages gradually reduced over five years.</p>
    <blockquote>« This reform aims to make the system fairer while preserving regional competitiveness. »</blockquote>
    <p>Our simulations show a net gain for urban middle-income households, but possible tensions in border areas.</p>`,
    tags: ["WAEMU", "economy", "taxation", "West Africa"],
    isFeatured: true,
    isTopStory: true,
    isUrgent: true,
    isEditorsChoice: true,
    isPremium: true,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=800&fit=crop",
    authorIndex: 0,
  },
  {
    title: "Wave and Orange Money announce merger: birth of Africa's first super-wallet",
    slug: "wave-et-orange-money-annoncent-leur-fusion-naissance-du-premier-super-portefeuille-africain",
    category: "finance",
    excerpt: "The deal would create an entity valued at over $8 billion, reshaping the FinTech landscape across the continent.",
    content: `<p>Two mobile money giants have just announced their intention to merge. The resulting entity would cover 24 countries and more than 180 million active users.</p>
    <h2>An expected consolidation</h2>
    <p>BCEAO and ARTP regulators must approve the deal by year-end. Analysts anticipate major synergies on cross-border transfers.</p>`,
    tags: ["FinTech", "Mobile Money", "merger", "Africa"],
    isTopStory: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&h=800&fit=crop",
    authorIndex: 0,
  },
  {
    title: "AFCON 2027: Félix Houphouët-Boigny Stadium to host the final, capacity raised to 60,000",
    slug: "can-2027-le-stade-felix-houphouet-boigny-accueillera-la-finale-capacite-portee-a-60-000",
    category: "sports",
    excerpt: "CAF has confirmed that Abidjan will host the continental tournament final after expansion work on the iconic stadium.",
    content: `<p>Côte d'Ivoire will host the AFCON 2027 final at the Félix Houphouët-Boigny Stadium, whose capacity will be increased to 60,000 seats. An investment of €120 million is planned.</p>`,
    tags: ["AFCON2027", "football", "Abidjan", "sport"],
    isTopStory: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Abidjan Tech Valley: 40 startups selected for the 2026 continental accelerator",
    slug: "abidjan-tech-valley-40-startups-selectionnees-pour-laccelerateur-continental-2026",
    category: "technologie",
    excerpt: "The program selects the most promising startups in West Africa for 12 months of support and a $2M fund.",
    content: `<p>Forty startups from 15 countries have been selected for the 2026 Abidjan Tech Valley cohort. Dominant sectors: agritech, digital health, and clean energy.</p>`,
    tags: ["startups", "tech", "Abidjan", "innovation"],
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "AU Summit: the continent adopts a roadmap for food self-sufficiency",
    slug: "sommet-de-lua-le-continent-adopte-une-feuille-de-route-pour-lautonomie-alimentaire",
    category: "monde",
    excerpt: "African heads of state adopted a five-year plan aiming to reduce food imports by 50% by 2031.",
    content: `<p>The extraordinary African Union summit resulted in a historic agreement on food self-sufficiency. The plan provides for $25 billion in public and private investment.</p>`,
    tags: ["AU", "agriculture", "food security", "Africa"],
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "Embezzlement of public funds: three ministers charged in construction contracts scandal",
    slug: "detournement-de-fonds-publics-trois-ministres-mis-en-examen-dans-laffaire-des-marches-de-construction",
    category: "investigations",
    excerpt: "Our eight-month investigation reveals a massive overbilling system in major infrastructure projects.",
    content: `<p>Three former ministers have been charged as part of a vast investigation into public construction contracts. Estimated losses exceed €400 million.</p>
    <h2>A sprawling network</h2>
    <p>Shell companies based in Dubai and Geneva allegedly laundered misappropriated funds over five years.</p>`,
    tags: ["investigation", "corruption", "infrastructure"],
    isTopStory: true,
    isUrgent: true,
    isEditorsChoice: true,
    isPremium: true,
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "Ivorian farmers turning cocoa into premium chocolate",
    slug: "ces-agriculteurs-ivoiriens-qui-transforment-le-cacao-en-chocolat-haut-de-gamme",
    category: "reportages-speciaux",
    excerpt: "A new generation of cocoa growers is disrupting the global chocolate market from plantations in Bélier.",
    content: `<p>In the Bélier region, family cooperatives now produce bean-to-bar chocolate exported to Europe and Asia. A model challenging the dominance of major processors.</p>`,
    tags: ["cocoa", "agriculture", "chocolate", "Côte d'Ivoire"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "RTS,S malaria vaccine: Côte d'Ivoire launches national mass vaccination campaign",
    slug: "vaccin-antipaludisme-rtss-la-cote-divoire-lance-sa-campagne-nationale-de-vaccination-de-masse",
    category: "sante",
    excerpt: "The Ministry of Health aims to vaccinate 2.5 million children in the first six months of the campaign.",
    content: `<p>Côte d'Ivoire becomes the first Francophone West African country to launch a mass malaria vaccination campaign with the RTS,S vaccine.</p>`,
    tags: ["health", "malaria", "vaccination"],
    isTopStory: true,
    image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "Google unveils its first sub-Saharan Africa data center in Accra",
    slug: "google-devoile-son-premier-data-center-dafrique-subsaharienne-installe-a-accra",
    category: "technologie",
    excerpt: "The $600 million investment positions Ghana as a regional digital hub.",
    content: `<p>Google has inaugurated its first sub-Saharan Africa data center in Accra. The facility will power cloud services for the entire West African region.</p>`,
    tags: ["Google", "data center", "Ghana", "tech"],
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Parliament passes personal data protection law",
    slug: "le-parlement-vote-la-loi-sur-la-protection-des-donnees-personnelles",
    subtitle: "A first in Francophone West Africa",
    category: "politique",
    excerpt: "The bill transposes international data protection standards and creates an independent supervisory authority.",
    content: `<p>Parliament adopted the personal data protection law by a large majority, a first in the Francophone West African space.</p>`,
    tags: ["personal data", "politics", "GDPR"],
    isTopStory: true,
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "AI for agriculture: Agrotech CI deploys voice assistant in Dioula and Baoulé",
    slug: "lia-au-service-de-lagriculture-agrotech-ci-deploie-son-assistant-vocal-en-dioula-et-baoule",
    category: "technologie",
    excerpt: "The app gives farmers personalized advice on crops, weather, and market prices.",
    content: `<p>Agrotech CI launches a multilingual voice assistant for smallholder farmers. The tool works offline and covers 12 main crops.</p>`,
    tags: ["AI", "agriculture", "innovation"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Should Francophone Africa rethink its public debt model?",
    slug: "faut-il-repenser-le-modele-de-la-dette-publique-en-afrique-francophone",
    category: "opinion",
    excerpt: "An economist's perspective on the limits of the current model and possible alternatives for Global South states.",
    content: `<p>African public debt has doubled in ten years. It is time to rethink borrowing mechanisms and repayment terms to free up resources for development.</p>`,
    tags: ["debt", "economy", "opinion"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "Ivoirians in France: how the second generation is reinventing ties with home",
    slug: "ivoiriens-de-france-comment-la-deuxieme-generation-reinvente-le-lien-avec-le-pays",
    category: "reportages-speciaux",
    excerpt: "Cross-portraits of eight young Franco-Ivoirians who chose to return home to start businesses.",
    content: `<p>They grew up in the Paris suburbs and chose to return to Abidjan to launch their startup or take over a family farm. Eight journeys telling the story of a changing diaspora.</p>`,
    tags: ["diaspora", "return", "entrepreneurship"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&h=800&fit=crop",
    authorIndex: 3,
  },
  {
    title: "Port of Abidjan: how it became West Africa's leading logistics hub",
    slug: "le-port-dabidjan-comment-il-est-devenu-le-premier-hub-logistique-dafrique-de-louest",
    category: "multimedia",
    excerpt: "Video report on the port's transformation into a continental logistics platform.",
    content: `<p>With 25 million tonnes of freight handled per year, the Port of Abidjan has become the commercial gateway to the West African hinterland.</p>`,
    tags: ["port", "logistics", "economy", "Abidjan"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    isFeatured: true,
    isTopStory: true,
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "Grand-Bassam UNESCO listing: extension of colonial heritage site officialized",
    slug: "grand-bassam-classee-au-patrimoine-mondial-lunesco-officialise-lextension-du-site-colonial",
    category: "local",
    excerpt: "The extension of the Grand-Bassam historic site strengthens Côte d'Ivoire's tourism and heritage appeal.",
    content: `<p>UNESCO has officialized the extension of the Grand-Bassam site to world heritage status, including newly restored colonial buildings.</p>`,
    tags: ["UNESCO", "heritage", "tourism", "Grand-Bassam"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200&h=800&fit=crop",
    authorIndex: 3,
  },
  {
    title: "UN adopts historic resolution on developing countries' sovereign debt",
    slug: "lonu-adopte-une-resolution-historique-sur-la-dette-souveraine-des-pays-en-developpement",
    category: "monde",
    excerpt: "The Security Council calls for coordinated restructuring of debt for the most vulnerable countries.",
    content: `<p>A historic resolution on sovereign debt was adopted at the UN, paving the way for fairer restructuring mechanisms for Global South countries.</p>`,
    tags: ["UN", "debt", "development"],
    image: "https://images.unsplash.com/photo-1540914124281-342587941389?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "Ligue 1 CI: ASEC wins Abidjan derby 3-1",
    slug: "ligue-1-ci-lasec-remporte-le-derby-dabidjan-3-1",
    category: "sports",
    excerpt: "ASEC Mimosas beat Africa Sports and reclaim the top of the Ivorian championship.",
    content: `<p>In a heated Abidjan derby, ASEC won 3-1 against Africa Sports at Robert-Champroux Stadium in front of 25,000 spectators.</p>`,
    tags: ["football", "ASEC", "Ligue 1", "Abidjan"],
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Sassandra deforestation: investigation reveals true scale of forest loss",
    slug: "deforestation-du-sassandra-lenquete-qui-revele-lampleur-reelle-des-pertes-forestieres",
    category: "investigations",
    excerpt: "Satellite imagery and local testimony document accelerated deforestation since 2020.",
    content: `<p>Our investigation cross-references satellite images, customs data, and villager testimony to quantify forest loss in the Sassandra region.</p>`,
    tags: ["environment", "deforestation", "investigation"],
    isEditorsChoice: true,
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  {
    title: "Global South Talks: African debt under the economists' microscope",
    slug: "global-south-talks-la-dette-africaine-sous-le-microscope-des-economistes",
    category: "opinion",
    excerpt: "Podcast episode with three experts on sovereign debt restructuring in Africa.",
    content: `<p>In this episode, our guests debate restructuring mechanisms, the IMF's role, and alternatives proposed by Global South countries.</p>`,
    tags: ["podcast", "debt", "economy"],
    contentType: "podcast",
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "AfDB announces $800M financing for Ivorian agri-food SMEs",
    slug: "la-bad-annonce-un-financement-de-800mdollar-pour-les-pme-ivoiriennes-dans-le-secteur-agroalimentaire",
    category: "finance",
    excerpt: "The African Development Bank unlocks a major package for local processing and agri-food exports.",
    content: `<p>The AfDB confirms an $800 million loan to support Ivorian SMEs.</p>`,
    tags: ["AfDB", "SMEs", "agri-food"],
    image: IMG.agriculture,
    authorIndex: 0,
  },
  {
    title: "United Nations: Security Council meets urgently on Sahel situation",
    slug: "nations-unies-le-conseil-de-securite-se-reunit-en-urgence-sur-la-situation-au-sahel",
    category: "monde",
    excerpt: "Deteriorating security in the Sahel puts the UN before a humanitarian and political dilemma.",
    content: `<p>The Security Council is holding an extraordinary session on the Sahel crisis.</p>`,
    tags: ["UN", "Sahel", "security"],
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "Meta deploys WhatsApp Pay in Côte d'Ivoire with native CinetPay integration",
    slug: "meta-deploie-son-service-whatsapp-pay-en-cote-divoire-avec-integration-cinetpay-native",
    category: "technologie",
    excerpt: "Payment via WhatsApp arrives in Côte d'Ivoire through a partnership with CinetPay.",
    content: `<p>Meta launches WhatsApp Pay in Côte d'Ivoire with CinetPay.</p>`,
    tags: ["Meta", "WhatsApp", "FinTech"],
    image: IMG.tech,
    authorIndex: 2,
  },
  {
    title: "New meningitis cases in Bouaké: Health Ministry activates regional emergency protocol",
    slug: "nouveaux-cas-de-meningite-a-bouake-le-ministere-de-la-sante-active-le-protocole-durgence-regional",
    category: "sante",
    excerpt: "Facing a surge in cases, health authorities deploy an emergency response.",
    content: `<p>Emergency protocol activated after new meningitis cases in Bouaké.</p>`,
    tags: ["health", "meningitis", "Bouaké"],
    isUrgent: true,
    image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1200&h=800&fit=crop",
    authorIndex: 5,
  },
  {
    title: "Exclusive interview: Prime Minister responds to criticism of education reform",
    slug: "interview-exclusive-le-premier-ministre-repond-aux-critiques-sur-la-reforme-de-leducation",
    category: "politique",
    excerpt: "The Prime Minister outlines the roadmap for national education reform.",
    content: `<p>Exclusive interview on education reform.</p>`,
    tags: ["politics", "education", "interview"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&h=800&fit=crop",
    authorIndex: 4,
  },
  {
    title: "The Elephants on the road to AFCON — report from the FIF training center",
    slug: "les-elephants-en-route-pour-la-can-reportage-dans-le-centre-de-preparation-de-la-fif",
    category: "sports",
    excerpt: "Inside the Ivorian national team's training center.",
    content: `<p>Report from the FIF training center.</p>`,
    tags: ["AFCON", "football"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=800&fit=crop",
    authorIndex: 2,
  },
  {
    title: "Illegal gold mining in the north: documentary on clandestine networks",
    slug: "orpaillage-illegal-dans-le-nord-le-grand-documentaire-sur-les-filieres-clandestines",
    category: "investigations",
    excerpt: "Documentary on illegal gold mining networks and their consequences.",
    content: `<p>Video investigation into clandestine gold mining in the north of the country.</p>`,
    tags: ["investigation", "gold mining"],
    contentType: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    isPremium: true,
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1200&h=800&fit=crop",
    authorIndex: 1,
  },
  // —— Africa ——
  {
    title: "AfCFTA implementation accelerates as Kenya and Ghana clear first tariff schedules",
    slug: "afcfta-implementation-accelerates-kenya-ghana-first-tariff-schedules",
    category: "africa",
    excerpt: "Two of the continent's largest economies have published binding tariff concessions, unlocking trade in goods across 54 member states.",
    content: `<p>Kenya and Ghana became the first major economies to file fully compliant tariff schedules under the African Continental Free Trade Area, a milestone negotiators have pursued since the agreement entered force in 2021.</p>`,
    tags: ["AfCFTA", "trade", "Kenya", "Ghana"],
    isFeatured: true,
    isTopStory: true,
    image: IMG.africa,
    authorIndex: 0,
  },
  {
    title: "Great Green Wall: fifteen years on, the Sahel reforestation project shows measurable gains",
    slug: "great-green-wall-sahel-reforestation-fifteen-years-progress",
    category: "africa",
    excerpt: "Satellite data confirms 18 million hectares restored across eleven Sahelian countries, though funding gaps persist.",
    content: `<p>The pan-African initiative to hold back desertification has crossed a symbolic threshold, with independent monitoring confirming sustained vegetation recovery in priority corridors.</p>`,
    tags: ["climate", "Sahel", "agriculture", "environment"],
    isEditorsChoice: true,
    image: IMG.sahel,
    authorIndex: 1,
  },
  {
    title: "Lagos–Abidjan corridor: ECOWAS approves $12 billion regional rail master plan",
    slug: "lagos-abidjan-corridor-ecowas-regional-rail-master-plan",
    category: "africa",
    excerpt: "The coastal rail link could cut freight times between West Africa's two largest ports by 40 percent.",
    content: `<p>ECOWAS transport ministers endorsed a phased construction plan linking Nigeria, Benin, Togo, Ghana, and Côte d'Ivoire.</p>`,
    tags: ["infrastructure", "ECOWAS", "transport", "West Africa"],
    image: IMG.port,
    authorIndex: 4,
  },
  {
    title: "Southern Africa mining royalties debate pits investors against resource nationalism",
    slug: "southern-africa-mining-royalties-debate-resource-nationalism",
    category: "africa",
    excerpt: "Zambia and Zimbabwe propose higher windfall taxes on copper and lithium exports, drawing pushback from major operators.",
    content: `<p>Governments argue that battery-metal demand justifies a larger public share of rents; mining houses warn of deferred capital expenditure.</p>`,
    tags: ["mining", "Zambia", "Zimbabwe", "economy"],
    image: IMG.economy,
    authorIndex: 5,
  },
  // —— Latin America ——
  {
    title: "Amazon Fund 2.0: Brazil attracts $2.4 billion in new pledges for rainforest protection",
    slug: "amazon-fund-brazil-2-4-billion-rainforest-protection-pledges",
    category: "latin-america",
    excerpt: "Norway, Germany, and a coalition of private foundations expand financing for indigenous land stewardship and enforcement.",
    content: `<p>President Lula's government presented an updated governance framework for the Amazon Fund at a donors' conference in Brasília.</p>`,
    tags: ["Brazil", "Amazon", "climate", "indigenous rights"],
    isFeatured: true,
    image: IMG.latinAmerica,
    authorIndex: 6,
  },
  {
    title: "Mexico nearshoring boom reshapes the industrial north as firms exit Asian supply chains",
    slug: "mexico-nearshoring-boom-industrial-north-supply-chains",
    category: "latin-america",
    excerpt: "Monterrey and Saltillo report record factory openings as US manufacturers diversify away from China.",
    content: `<p>Industrial parks near the US border are operating at capacity, with wait lists for skilled welders and automation engineers.</p>`,
    tags: ["Mexico", "manufacturing", "trade", "nearshoring"],
    isTopStory: true,
    image: IMG.economy,
    authorIndex: 6,
  },
  {
    title: "Colombia peace process: rural councils gain budget autonomy in historic decentralization law",
    slug: "colombia-peace-process-rural-councils-budget-autonomy",
    category: "latin-america",
    excerpt: "Former conflict zones will control 30 percent of national rural development spending under legislation passed in Bogotá.",
    content: `<p>The law implements a key provision of the 2016 peace accord, transferring planning powers to municipal assemblies in the Pacific and Amazon regions.</p>`,
    tags: ["Colombia", "peace", "governance", "rural development"],
    image: IMG.forest,
    authorIndex: 6,
  },
  {
    title: "Argentina and Brazil launch joint study on a common trade currency for Mercosur",
    slug: "argentina-brazil-common-trade-currency-mercosur-study",
    category: "latin-america",
    excerpt: "Leaders frame the initiative as a complement—not a replacement—for existing monetary systems.",
    content: `<p>Central bank technical teams will model settlement mechanisms for bilateral trade invoiced outside the US dollar.</p>`,
    tags: ["Argentina", "Brazil", "Mercosur", "finance"],
    image: IMG.finance,
    authorIndex: 0,
  },
  // —— South Asia ——
  {
    title: "India exports its digital public infrastructure model to Bangladesh and Sri Lanka",
    slug: "india-digital-public-infrastructure-export-bangladesh-sri-lanka",
    category: "south-asia",
    excerpt: "Unified payments, digital identity, and open APIs are packaged as a turnkey stack for emerging economies.",
    content: `<p>New Delhi signed framework agreements to adapt UPI-style rails and Aadhaar-inspired identity systems with two neighbors.</p>`,
    tags: ["India", "digital", "UPI", "governance"],
    isFeatured: true,
    image: IMG.southAsia,
    authorIndex: 7,
  },
  {
    title: "Bangladesh garment sector adopts living wage framework after global brand pressure",
    slug: "bangladesh-garment-sector-living-wage-framework",
    category: "south-asia",
    excerpt: "Factory owners and unions agree on a phased minimum tied to inflation in Dhaka and Chattogram industrial zones.",
    content: `<p>The accord follows months of negotiations brokered by the International Labour Organization.</p>`,
    tags: ["Bangladesh", "labour", "textiles", "trade"],
    isEditorsChoice: true,
    image: IMG.port,
    authorIndex: 7,
  },
  {
    title: "Indus Waters Treaty talks resume as Pakistan and India seek mediation after a decade of silence",
    slug: "indus-waters-treaty-talks-pakistan-india-mediation",
    category: "south-asia",
    excerpt: "World Bank officials convene technical working groups on river flow data and dispute resolution.",
    content: `<p>Both governments cite climate-driven variability in Himalayan runoff as justification for updating the 1960 agreement.</p>`,
    tags: ["Pakistan", "India", "water", "diplomacy"],
    image: IMG.un,
    authorIndex: 7,
  },
  {
    title: "Sri Lanka tourism recovery surpasses pre-crisis arrivals as diaspora returns en masse",
    slug: "sri-lanka-tourism-recovery-pre-crisis-arrivals",
    category: "south-asia",
    excerpt: "Colombo hotels report 92 percent occupancy during the April festival season.",
    content: `<p>Currency stabilization and visa liberalization have restored confidence among European and Gulf travelers.</p>`,
    tags: ["Sri Lanka", "tourism", "economy", "diaspora"],
    image: IMG.heritage,
    authorIndex: 7,
  },
  // —— West Asia ——
  {
    title: "Gulf states pledge $40 billion for African energy transition projects",
    slug: "gulf-states-40-billion-african-energy-transition",
    category: "west-asia",
    excerpt: "Saudi Arabia and the UAE target solar, green hydrogen, and grid interconnections across the Sahel and East Africa.",
    content: `<p>The commitment was announced at a Riyadh summit pairing Gulf sovereign funds with African infrastructure ministries.</p>`,
    tags: ["Gulf", "energy", "Africa", "investment"],
    isFeatured: true,
    isTopStory: true,
    image: IMG.westAsia,
    authorIndex: 8,
  },
  {
    title: "Iran nuclear talks: regional ripple effects on oil markets and shipping insurance",
    slug: "iran-nuclear-talks-regional-oil-markets-shipping",
    category: "west-asia",
    excerpt: "Analysts weigh scenarios for Strait of Hormuz traffic if sanctions relief is partial or delayed.",
    content: `<p>Energy traders are pricing in a narrow band of volatility as diplomats resume indirect negotiations in Muscat.</p>`,
    tags: ["Iran", "energy", "diplomacy", "oil"],
    image: IMG.economy,
    authorIndex: 8,
  },
  {
    title: "Turkey brokers extension of Black Sea grain corridor with UN backing",
    slug: "turkey-black-sea-grain-corridor-extension-un",
    category: "west-asia",
    excerpt: "Ankara positions itself as indispensable mediator between Kyiv, Moscow, and global food importers.",
    content: `<p>The renewed memorandum keeps inspection protocols in place for Odessa-area ports through year-end.</p>`,
    tags: ["Turkey", "grain", "Ukraine", "food security"],
    isUrgent: true,
    image: IMG.port,
    authorIndex: 8,
  },
  {
    title: "Saudi Arabia unveils megacity solar hub targeting 50 GW of desert photovoltaic capacity",
    slug: "saudi-arabia-megacity-solar-hub-50-gw-photovoltaic",
    category: "west-asia",
    excerpt: "NEOM's energy subsidiary signs offtake deals with European industrial buyers.",
    content: `<p>Officials say the project will pair panel manufacturing with green hydrogen export terminals on the Red Sea.</p>`,
    tags: ["Saudi Arabia", "NEOM", "solar", "hydrogen"],
    isPremium: true,
    image: IMG.datacenter,
    authorIndex: 8,
  },
  // —— Entertainment ——
  {
    title: "Afrobeats goes global: Lagos and Abidjan producers dominate streaming charts",
    slug: "afrobeats-goes-global-lagos-abidjan-streaming-charts",
    category: "divertissement",
    excerpt: "A new wave of West African artists tops international playlists, reshaping how labels scout talent south of the Sahara.",
    content: `<p>Streaming platforms report record growth for Afrobeats and coupé-décalé crossovers, with independent producers in Lagos and Abidjan signing direct distribution deals.</p>`,
    tags: ["music", "Afrobeats", "Nigeria", "Côte d'Ivoire"],
    isFeatured: true,
    image: IMG.portrait1,
    authorIndex: 3,
  },
  {
    title: "FESPACO 2026: Burkina Faso film festival spotlights Sahelian directors",
    slug: "fespaco-2026-burkina-faso-sahelian-directors",
    category: "divertissement",
    excerpt: "The pan-African cinema showcase returns with a record number of submissions from conflict-affected countries.",
    content: `<p>FESPACO's 2026 edition highlights filmmakers from Mali, Niger, and Burkina Faso, with a dedicated program on cinema as cultural resistance.</p>`,
    tags: ["cinema", "FESPACO", "Burkina Faso", "culture"],
    isEditorsChoice: true,
    image: IMG.heritage,
    authorIndex: 1,
  },
  {
    title: "Nollywood on Netflix: Nigerian studios negotiate landmark revenue-sharing deal",
    slug: "nollywood-netflix-nigerian-studios-revenue-sharing",
    category: "divertissement",
    excerpt: "Studios secure improved royalties and regional premiere windows for original series aimed at diaspora audiences.",
    content: `<p>After months of talks, Nigeria's leading production houses reached a framework agreement with Netflix for African originals.</p>`,
    tags: ["Nollywood", "streaming", "Nigeria", "film"],
    image: IMG.latinAmerica,
    authorIndex: 6,
  },
  {
    title: "Abidjan Fashion Week: designers blend wax prints with sustainable textiles",
    slug: "abidjan-fashion-week-sustainable-wax-prints",
    category: "divertissement",
    excerpt: "Runway shows spotlight eco-friendly fabrics and artisan cooperatives from across West Africa.",
    content: `<p>Abidjan Fashion Week closed with a collective showcase of designers using recycled materials and traditional weaving techniques.</p>`,
    tags: ["fashion", "Abidjan", "culture", "sustainability"],
    image: IMG.diaspora,
    authorIndex: 3,
  },
  // —— Infographics & galleries ——
  {
    title: "WAEMU debt in numbers: who owes what across eight member states",
    slug: "waemu-debt-in-numbers-eight-member-states-infographic",
    category: "finance",
    excerpt: "An interactive visual breakdown of sovereign and commercial debt across the West African Economic and Monetary Union.",
    content: `<p>Our data desk maps debt-to-GDP ratios, repayment schedules, and creditor composition for Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, and Togo.</p>`,
    tags: ["infographic", "WAEMU", "debt", "data"],
    isFeatured: true,
    image: IMG.economy,
    authorIndex: 0,
  },
  {
    title: "Malaria by district: mapping vaccination rollout across Côte d'Ivoire",
    slug: "malaria-by-district-vaccination-rollout-cote-divoire-infographic",
    category: "sante",
    excerpt: "District-level heat maps show where the RTS,S campaign has reached children under five.",
    content: `<p>Health ministry open data visualized for public transparency.</p>`,
    tags: ["infographic", "health", "malaria", "maps"],
    image: IMG.health,
    authorIndex: 5,
  },
  {
    title: "AfCFTA trade flows: a visual guide to continental exchange",
    slug: "afcfta-trade-flows-visual-guide-infographic",
    category: "africa",
    excerpt: "Charts and maps explain which corridors are gaining volume under the African Continental Free Trade Area.",
    content: `<p>Trade data from 2024–2026 visualized for policymakers and business readers.</p>`,
    tags: ["infographic", "AfCFTA", "trade", "Africa"],
    image: IMG.africa,
    authorIndex: 0,
  },
  {
    title: "Grand-Bassam in pictures: UNESCO heritage extension photo essay",
    slug: "grand-bassam-unesco-heritage-photo-essay",
    category: "local",
    excerpt: "Twelve frames documenting restored colonial architecture and community life along the lagoon.",
    content: `<p>A photographic walk through the expanded UNESCO site with captions from local historians.</p>`,
    tags: ["gallery", "heritage", "UNESCO", "photography"],
    contentType: "gallery",
    gallery: [
      { url: IMG.heritage, caption: "Restored waterfront façade" },
      { url: IMG.port, caption: "Fishing boats at dawn" },
    ],
    isEditorsChoice: true,
    image: IMG.heritage,
    authorIndex: 3,
  },
  {
    title: "Sassandra forest loss: satellite imagery gallery 2020–2026",
    slug: "sassandra-forest-loss-satellite-gallery",
    category: "investigations",
    excerpt: "Before-and-after satellite frames document accelerated deforestation in western Côte d'Ivoire.",
    content: `<p>Visual evidence supporting our investigation into illegal logging networks.</p>`,
    tags: ["gallery", "environment", "investigation", "satellite"],
    contentType: "gallery",
    gallery: [
      { url: IMG.forest, caption: "Canopy cover 2020" },
      { url: IMG.sahel, caption: "Clearing patterns 2024" },
    ],
    image: IMG.forest,
    authorIndex: 1,
  },
  {
    title: "Lagos street markets: a photo report on informal trade",
    slug: "lagos-street-markets-photo-report-informal-trade",
    category: "africa",
    excerpt: "Portraits and street scenes from Balogun and Idumota markets at the heart of West Africa's largest city.",
    content: `<p>Photo essay on traders navigating currency swings and infrastructure gaps.</p>`,
    tags: ["gallery", "Nigeria", "economy", "photography"],
    contentType: "gallery",
    gallery: [
      { url: IMG.port, caption: "Textile traders, Balogun Market" },
      { url: IMG.latinAmerica, caption: "Electronics corridor at dusk" },
    ],
    image: IMG.port,
    authorIndex: 6,
  },
];

export const SEED_NEWSLETTER = [
  { email: "lecteur1@example.com", preferences: ["general", "finance"] },
  { email: "lecteur2@example.com", preferences: ["sports", "general"] },
  { email: "redaction@globalsouthwatch.test", preferences: ["investigations", "opinion"] },
];
